version: "3"
services:
  api-server:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    image: asic-guanipa:latest
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./:/app"
    links:
      - db-postgres
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
