services:
  api-server:
    env_file: .env
    environment:
      DB_HOST: db-postgres
      DB_PORT: 5432
    build:
      context: ./
      dockerfile: Dockerfile
    image: asic-guanipa:latest
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./:/app"
    links:
      - db-postgres
    depends_on:
      db-postgres:
        condition: service_healthy

  db-postgres:
    image: postgres:17-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
