name: Run Jest Tests

on:
  push:
    branches:
      - "main"
      - "feature/*"
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI_DB_NAME: cdi_ci
      DB_NAME: cdi_ci
      DB_HOST: localhost
      DB_USER: username_ci
      DB_PASSWORD: password_ci
      DB_PORT: 5432
      JWT_SECRET: tu_secreto_jwt_super_seguro_cambialo
      JWT_EXPIRE: 24h
      ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      NODE_ENV: test
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: username_ci
          POSTGRES_PASSWORD: password_ci
          POSTGRES_DB: cdi_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U username_ci && break
            sleep 2
          done

      - name: Install dependencies
        run: npm install

      - name: Setup Database
        run: |
          npx sequelize-cli db:migrate --env test
          npx sequelize-cli db:seed:all --env test

      - name: Run Jest tests
        run: DB_HOST=localhost npx jest --runInBand --coverage
