name: Run Jest Tests

on:
  push:
    branches: [main, feature/cd]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI_DB_NAME: cdi_ci
      DB_HOST: postgres
      DB_USER: username_ci
      DB_PASSWORD: password_ci
      DB_PORT: 5432
      NODE_ENV: test

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${CI_DB_NAME}
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Adding Path
        run: |
          apt install postgres-client -y |
          sleep 10 |
          npx sequelize db:create || exit 1 |
          npx sequelize db:migrate || exit 1
          npx sequelize db:seed:all || exit 1

      - name: Run Jest tests
        run: npx jest --runInBand --coverage
